from . import views
from django.urls import path,re_path

urlpatterns = [
    path("",views.home, name='home'),
    path("a",views.error1, name='v1030'),
    path("b",views.about1, name='v1040'),
    path("c",views.contact1, name='v1050'),
    path("d",views.login1, name='v1060'),
    path("e",views.mashq1, name='v1070'),
    path("extr",views.extra, name='ex10'),
    path("qosh",views.qoshim, name='qosh10'),
    path("qoshim/<int:pk>", views.qoshim, name='qosh10'),
    path("unv",views.unver, name='unv10'),
    # re_path(r'^qoshim/(?P<id>\w+)/$', views.qoshim, name='qosh10'),
    ###########################################A
    path("09",views.aharf, name='a1010'),
    path("A0",views.aharf0, name='aharf0'),
    path("A1",views.aharf1, name='aharf1'),
    path("A2",views.aharf2, name='aharf2'),
    path("A3",views.aharf3, name='aharf3'),
    path("A4",views.aharf4, name='aharf4'),
    path("A5",views.aharf5, name='aharf5'),
   ###########################################B
    path("B8",views.bharf, name= 'b1010'),
    path("B0",views.bharf0, name='bharf0'),
    path("B1",views.bharf1, name='bharf1'),
    path("B2",views.bharf2, name='bharf2'),
    path("B3",views.bharf3, name='bharf3'),
    path("B4",views.bharf4, name='bharf4'),
    path("B5",views.bharf5, name='bharf5'),
    #############################################D
    path("17",views.dharf, name='d1010'),
    path("D0",views.dharf0, name='dharf0'),
    path("D1",views.dharf1, name='dharf1'),
    path("D2",views.dharf2, name='dharf2'),
    path("D3",views.dharf3, name='dharf3'),
    path("D4",views.dharf4, name='dharf4'),
    path("D5",views.dharf5, name='dharf5'),
###########################################E
    path("18",views.eharf, name='e1010'),
    path("E0",views.eharf0, name='eharf0'),
    path("E1",views.eharf1, name='eharf1'),
    path("E2",views.eharf2, name='eharf2'),
    path("E3",views.eharf3, name='eharf3'),
    path("E4",views.eharf4, name='eharf4'),
    path("E5",views.eharf5, name='eharf5'),
###########################################F
    path("F8",views.fharf,  name='f1010'),
    path("F0",views.fharf0, name='fharf0'),
    path("F1",views.fharf1, name='fharf1'),
    path("F2",views.fharf2, name='fharf2'),
    path("F3",views.fharf3, name='fharf3'),
    path("F4",views.fharf4, name='fharf4'),
    path("F5",views.fharf5, name='fharf5'),
###########################################G
    path("G8",views.gharf,  name='g1010'),
    path("G0",views.gharf0, name='gharf0'),
    path("G1",views.gharf1, name='gharf1'),
    path("G2",views.gharf2, name='gharf2'),
    path("G3",views.gharf3, name='gharf3'),
    path("G4",views.gharf4, name='gharf4'),
    path("G5",views.gharf5, name='gharf5'),
###########################################H
    path("H8",views.hharf,  name='h1010'),
    path("H0",views.hharf0, name='hharf0'),
    path("H1",views.hharf1, name='hharf1'),
    path("H2",views.hharf2, name='hharf2'),
    path("H3",views.hharf3, name='hharf3'),
    path("H4",views.hharf4, name='hharf4'),
    path("H5",views.hharf5, name='hharf5'),
###########################################I
    path("I8",views.iharf,  name='i1010'),
    path("I0",views.iharf0, name='iharf0'),
    path("I1",views.iharf1, name='iharf1'),
    path("I2",views.iharf2, name='iharf2'),
    path("I3",views.iharf3, name='iharf3'),
    path("I4",views.iharf4, name='iharf4'),
    path("I5",views.iharf5, name='iharf5'),
###########################################J
    path("J8",views.jharf,  name='j1010'),
    path("J0",views.jharf0, name='jharf0'),
    path("J1",views.jharf1, name='jharf1'),
    path("J2",views.jharf2, name='jharf2'),
    path("J3",views.jharf3, name='jharf3'),
    path("J4",views.jharf4, name='jharf4'),
    path("J5",views.jharf5, name='jharf5'),
###########################################K
    path("K8",views.kharf,  name='k1010'),
    path("K0",views.kharf0, name='kharf0'),
    path("K1",views.kharf1, name='kharf1'),
    path("K2",views.kharf2, name='kharf2'),
    path("K3",views.kharf3, name='kharf3'),
    path("K4",views.kharf4, name='kharf4'),
    path("K5",views.kharf5, name='kharf5'),
###########################################L
    path("L8",views.lharf,  name='l1010'),
    path("L0",views.lharf0, name='lharf0'),
    path("L1",views.lharf1, name='lharf1'),
    path("L2",views.lharf2, name='lharf2'),
    path("L3",views.lharf3, name='lharf3'),
    path("L4",views.lharf4, name='lharf4'),
    path("L5",views.lharf5, name='lharf5'),
###########################################M
    path("M8",views.mharf,  name='m1010'),
    path("M0",views.mharf0, name='mharf0'),
    path("M1",views.mharf1, name='mharf1'),
    path("M2",views.mharf2, name='mharf2'),
    path("M3",views.mharf3, name='mharf3'),
    path("M4",views.mharf4, name='mharf4'),
    path("M5",views.mharf5, name='mharf5'),
###########################################N
    path("N8",views.nharf,  name='n1010'),
    path("N0",views.nharf0, name='nharf0'),
    path("N1",views.nharf1, name='nharf1'),
    path("N2",views.nharf2, name='nharf2'),
    path("N3",views.nharf3, name='nharf3'),
    path("N4",views.nharf4, name='nharf4'),
    path("N5",views.nharf5, name='nharf5'),
###########################################O
    path("O8",views.oharf,  name='o1010'),
    path("O0",views.oharf0, name='oharf0'),
    path("O1",views.oharf1, name='oharf1'),
    path("O2",views.oharf2, name='oharf2'),
    path("O3",views.oharf3, name='oharf3'),
    path("O4",views.oharf4, name='oharf4'),
    path("O5",views.oharf5, name='oharf5'),
###########################################P
    path("P8",views.pharf,  name='p1010'),
    path("P0",views.pharf0, name='pharf0'),
    path("P1",views.pharf1, name='pharf1'),
    path("P2",views.pharf2, name='pharf2'),
    path("P3",views.pharf3, name='pharf3'),
    path("P4",views.pharf4, name='pharf4'),
    path("P5",views.pharf5, name='pharf5'),
###########################################Q
    path("Q8",views.qharf,  name='q1010'),
    path("Q0",views.qharf0, name='qharf0'),
    path("Q1",views.qharf1, name='qharf1'),
    path("Q2",views.qharf2, name='qharf2'),
    path("Q3",views.qharf3, name='qharf3'),
    path("Q4",views.qharf4, name='qharf4'),
    path("Q5",views.qharf5, name='qharf5'),
###########################################R
    path("R8",views.rharf,  name='r1010'),
    path("R0",views.rharf0, name='rharf0'),
    path("R1",views.rharf1, name='rharf1'),
    path("R2",views.rharf2, name='rharf2'),
    path("R3",views.rharf3, name='rharf3'),
    path("R4",views.rharf4, name='rharf4'),
    path("R5",views.rharf5, name='rharf5'),
###########################################S
    path("S8",views.sharf,  name='s1010'),
    path("S0",views.sharf0, name='sharf0'),
    path("S1",views.sharf1, name='sharf1'),
    path("S2",views.sharf2, name='sharf2'),
    path("S3",views.sharf3, name='sharf3'),
    path("S4",views.sharf4, name='sharf4'),
    path("S5",views.sharf5, name='sharf5'),
###########################################T
    path("T8",views.tharf,  name='t1010'),
    path("T0",views.tharf0, name='tharf0'),
    path("T1",views.tharf1, name='tharf1'),
    path("T2",views.tharf2, name='tharf2'),
    path("T3",views.tharf3, name='tharf3'),
    path("T4",views.tharf4, name='tharf4'),
    path("T5",views.tharf5, name='tharf5'),
###########################################U
    path("U8",views.uharf,  name='u1010'),
    path("U0",views.uharf0, name='uharf0'),
    path("U1",views.uharf1, name='uharf1'),
    path("U2",views.uharf2, name='uharf2'),
    path("U3",views.uharf3, name='uharf3'),
    path("U4",views.uharf4, name='uharf4'),
    path("U5",views.uharf5, name='uharf5'),
###########################################V
    path("V8",views.vharf,  name='v1010'),
    path("V0",views.vharf0, name='vharf0'),
    path("V1",views.vharf1, name='vharf1'),
    path("V2",views.vharf2, name='vharf2'),
    path("V3",views.vharf3, name='vharf3'),
    path("V4",views.vharf4, name='vharf4'),
    path("V5",views.vharf5, name='vharf5'),
###########################################X
    path("X8",views.xharf,  name='x1010'),
    path("X0",views.xharf0, name='xharf0'),
    path("X1",views.xharf1, name='xharf1'),
    path("X2",views.xharf2, name='xharf2'),
    path("X3",views.xharf3, name='xharf3'),
    path("X4",views.xharf4, name='xharf4'),
    path("X5",views.xharf5, name='xharf5'),
###########################################Y
    path("Y8",views.yharf,  name='y1010'),
    path("Y0",views.yharf0, name='yharf0'),
    path("Y1",views.yharf1, name='yharf1'),
    path("Y2",views.yharf2, name='yharf2'),
    path("Y3",views.yharf3, name='yharf3'),
    path("Y4",views.yharf4, name='yharf4'),
    path("Y5",views.yharf5, name='yharf5'),
###########################################Z
    path("Z8",views.zharf,  name='z1010'),
    path("Z0",views.zharf0, name='zharf0'),
    path("Z1",views.zharf1, name='zharf1'),
    path("Z2",views.zharf2, name='zharf2'),
    path("Z3",views.zharf3, name='zharf3'),
    path("Z4",views.zharf4, name='zharf4'),
    path("Z5",views.zharf5, name='zharf5'),
    ]