# Generated by Django 4.1.6 on 2023-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harflar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uploaded_file', models.FileField(upload_to='')),
                ('photo', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('description', models.TextField()),
            ],
        ),
    ]
