# Generated by Django 4.1.6 on 2023-03-06 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harflar2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uploaded_file', models.FileField(upload_to='')),
                ('photo', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('description', models.TextField()),
                ('harflar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.harflar')),
            ],
        ),
    ]
