# Generated by Django 4.1.6 on 2023-03-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_harflar2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harflar',
            name='description',
        ),
        migrations.AlterField(
            model_name='harflar',
            name='name',
            field=models.CharField(max_length=100, verbose_name="So'z"),
        ),
        migrations.AlterField(
            model_name='harflar',
            name='uploaded_file',
            field=models.FileField(upload_to='', verbose_name='ovoz'),
        ),
        migrations.DeleteModel(
            name='Harflar2',
        ),
    ]
